name: PocketMobs
version: 1.1.0
main: dev.lone.pocketmobs.Main
api-version: 1.13
authors: [LoneDev]
depend:
  - LoneLibs
softdepend:
  - Vault
  - Essentials
  - ProtocolLib
commands:
  pocketmob:
    usage: /<command> [args]
    aliases: [pocketmobs, pmob, pmobs]